### ISSUE TITLE
In the Pandas/Polars Rosetta Stone, a couple notes

### ISSUE THREAD

**Issue by deanm0000** [WinVector/Examples#1]
Polars contexts aren't big sticklers for receiving lists.

For example 

```
peng_pl.filter(pl.col("species") == "Chinstrap").select(
    ["species", "island", "body_mass_g"]
)
```

could just be

```
peng_pl.filter(pl.col("species") == "Chinstrap").select(
    "species", "island", "body_mass_g"
)
```

This is essentially because they accept **kwargs. Another even more useful benefit to that is you can add new columns as named parameters so instead of 

```
peng_pl = peng_pl.with_columns(
    [(pl.col("bill_length_mm") * pl.col("bill_depth_mm")).alias("biil_volume")]
)
```

you can write

```
peng_pl = peng_pl.with_columns(
   biil_volume=pl.col("bill_length_mm") * pl.col("bill_depth_mm")
)
```

**Comment by NinaZumel** [comment]
Thank you for the notes, and apologies for the delay in responding. I personally prefer lists, so I've kept the `select` call as is, with a note that your example also works, since I suspect I am in the minority about my preference.

Added your second note as well (and kept the original). 

Again, thank you; improvements are appreciated.
